# Generated by Django 4.2.13 on 2024-07-28 13:50

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustumeFriendShip',
            new_name='CustomeFriendShip',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_sender',
            new_name='message_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_reciever',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/uploads/user-default.png', upload_to=api.models.uploads),
        ),
        migrations.CreateModel(
            name='CustomeChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
