# Generated by Django 5.0.4 on 2024-05-02 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_match_friendship_message_usermatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermatch',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='api.match'),
            preserve_default=False,
        ),
    ]
