# Generated by Django 5.0.4 on 2024-05-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
