# Generated by Django 4.2.13 on 2024-05-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_message_chat_room_alter_chatroom_user1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
