# Generated by Django 4.2.13 on 2024-05-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_tmpmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='response_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
