# Generated by Django 4.2.13 on 2024-05-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_friendship_response_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together={('friend_ship_sender', 'friend_ship_reciever')},
        ),
    ]
