# Generated by Django 4.2.13 on 2024-06-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_friendship_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('user1', 'user2')},
        ),
    ]
