# Generated by Django 4.2.13 on 2024-07-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_chatroom_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chatroom',
            name='unique_users_in_chatroom',
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('user1', 'user2')},
        ),
    ]
