# Generated by Django 4.2.13 on 2024-07-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_user_avatar_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermatch',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='usertournament',
            name='winner',
        ),
    ]
