# Generated by Django 5.1.2 on 2024-10-23 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_code_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticTacToeMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('player1_score', models.IntegerField(blank=True, default=0)),
                ('player2_score', models.IntegerField(blank=True, default=0)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tictactoe_match_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tictactoe_match_player2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ticTacToeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_number', models.IntegerField(default=0)),
                ('number_matches', models.IntegerField(default=0)),
                ('number_wins', models.IntegerField(default=0)),
                ('numbers_losers', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tictactoe_score_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
