# Generated by Django 5.1.3 on 2024-11-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tictactoematch_tictactoescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='chat_type',
            field=models.IntegerField(default=0),
        ),
    ]
