version: '3.9'

services:

  backend:
    build: ./backend/
    container_name: backend
    restart: always
    ports:
      - 8000:8000
    volumes:
      - backend:/my_app

    environment:
      - INTRA_UID=${INTRA_UID}
      - INTRA_SECRET=${INTRA_SECRET}
      - BACKEND_URL=${BACKEND_URL}
      - INTRA_API=${INTRA_API}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

  frontend:
    build: ./frontend/
    container_name: frontend
    restart: always
    ports:
      - 3001:80
    volumes:
      - frontend:/usr/share/nginx/html
  

  reactfront:
    build: ./reactfront/
    container_name: reactfront
    restart: always
    ports:
      - 3000:3000
    volumes:
      - reactfront:/r-tuto/


  # db:
  #   image: postgres
  #   restart: always
  #   shm_size: 128mb
  #   container_name: db
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_PASSWORD=${DB_PASSWORD}
  #     POSTGRES_USER=${DB_USER}
  #     POSTGRES_DB:=${DB_NAME}


  # adminer:
  #   image: adminer
  #   restart: always
  #   container_name: adminer
  #   ports:
  #     - 8080:8080

  redis:
    image: redis:7
    restart: always
    container_name: redis
    ports:
      - 6370:6379
  

volumes:
  backend:
    driver: local
    name: backend
    driver_opts:
      type: none
      o: bind
      # device: /home/haghouli/Desktop/ft_transcendence/backend/
      device: /nfs/homes/haghouli/Desktop/ft_transcendence/backend/
      # device: C:\Users\HiChaM\Desktop\Files\ft_transcendence\backend\
  

  frontend:
    driver: local
    name: frontend
    driver_opts:
      type: none
      o: bind
      # device: /home/haghouli/Desktop/ft_transcendence/frontend/
      device: /nfs/homes/haghouli/Desktop/ft_transcendence/frontend/
      # device: C:\Users\HiChaM\Desktop\Files\ft_transcendence\frontend\
    
  reactfront:
    driver: local
    name: react-front
    driver_opts:
      type: none
      o: bind
      # device: /home/haghouli/Desktop/ft_transcendence/frontend/
      device: /nfs/homes/haghouli/Desktop/ft_transcendence/reactfront/
      # device: C:\Users\HiChaM\Desktop\Files\ft_transcendence\frontend\