version: '3.9'

services:

  nginx:
    build: ./nginx/
    container_name: nginx
    restart: always
    ports:
      - 3000:443

  django:
    build: ./django/
    container_name: django
    restart: always
    ports:
      - 8000:8000
    
    depends_on:
      - db
    

    environment:
      - INTRA_UID=${INTRA_UID}
      - INTRA_SECRET=${INTRA_SECRET}
      - BACKEND_URL=${BACKEND_URL}
      - INTRA_API=${INTRA_API}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DJANGO_SETTINGS_MODULE=my_project.settings
      - DOMAIN_NAME=${DOMAIN_NAME}
      - BACKEND_SECRET_KEY=${BACKEND_SECRET_KEY}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_PORT=${EMAIL_PORT}

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080

  redis:
    image: redis:7
    restart: always
    container_name: redis
    ports:
      - 6370:6379
